// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NetworkMessage
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public enum eChatType : sbyte
{
  CT_System = 0,
  CT_Say = 1,
  CT_Chat = 2,
  CT_Guild = 3,
  CT_Help = 4,
};

public enum eChatLoc : sbyte
{
  CL_ChatWindow = 0,
  CL_PopupWindow = 1,
  CL_SystemWindow = 2,
};

public enum ServerPackets : ushort
{
  SC_LoginAns = 1,
  SC_AccountInfo = 2,
  SC_StringMessage = 3,
};

public enum ClientPackets : ushort
{
  CS_LoginReq = 1,
  CS_WorldJoinReq = 2,
  CS_UpdatePosition = 3,
};


}
